version: '3.3'

services:
   db:
     image: postgres:13.0-alpine
     volumes:
    #    - db_data:/var/lib/postgresql/data
       - /Users/goline/TienNK/DevOps/db:/var/lib/postgresql/data
       - /Users/goline/TienNK/DevOps/nodejs-todolist/init.sql:/docker-entrypoint-initdb.d/init.sql
     restart: always
     environment:
       POSTGRES_PASSWORD: postgres

   nodeapp:
     depends_on:
       - db
     image: node1
     ports:
       - "8899:8080"
     restart: always
volumes:
    db_data: {}